# Site settings
author: Indre Bakeer
title: CLI Data Gem Project 
header-img: img/home-bg.png
email: indre.bakeer@gmail.com
copyright_name: Indre Bakeer
description: > # this means to ignore newlines until "baseurl:"
  Steps and description of my first CLI project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  indre93

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
